name: Update addons data
on:
    workflow_dispatch:
        inputs:
            Version:
                required: false
                type: string
    schedule:
        - cron: 30 11/12 * * *

permissions: write-all

jobs:
    update:
        name: Update
        runs-on: ubuntu-20.04

        steps:
            # Clone
            - uses: actions/checkout@v4.1.0
              with:
                  repository: ScratchAddons/ScratchAddons
                  sparse-checkout: |
                      ./addons/*/addon.json
                      ./addons/addons.json
                  sparse-checkout-cone-mode: false
                  fetch-tags: true
            - run: ls -a
            # Checkout
            - run: VERSION="${{ inputs.Version || env.LATEST }}"
              env:
                  LATEST: $(git rev-list --tags --timestamp --no-walk | sort -nr | head -n1 | cut -f 2 -d ' ')
            - run: git checkout $VERSION
            # Get package
            - run: ls -a
            - run: ls .. -a
            - run: mkdir ./dist
            - run: echo "{\"name\":\"@sa-community/addons-data\",\"version\":\"$VERSION\",\"description\":Scratch Addons\" addons data\",\"homepage\":\"https://github.com/scratchaddons-community\",\"repository\":\"git+https://github.com/scratchaddons-community/addons-data-script\",\"license\":\"GPLv3\",\"maintainers\":[\"RedGuy12\"],\"main\":\"addons.json\"}" > ./dist/package.json
            # Get addons
            - run: echo [ > ./dist/addons.json
            - run: ls -a
            - run: ls .. -a
            - run: addons = $(jq -r '.[]' ./addons/addons.json)
            - run: |
                  for addon in "${addons[@]}"; do
                    cat "./addons/$addon/addon.json" >> ./dist/addons.json
                    echo , >> ./dist/addons.json
                  done
            - run: echo ] >> ./dist/addons.json
            # Publish
            - uses: actions/setup-node@v3
              with:
                  registry-url: "https://registry.npmjs.org"
            # - run: npm publish
            #   working-directory: ./dist
            #   env:
            #       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
