name: Update addons data
on:
    push:
        branches: main
    workflow_dispatch:
        inputs:
            Version:
                required: false
                type: string
    schedule:
        - cron: 30 11/12 * * *

permissions: write-all

jobs:
    update:
        name: Update
        runs-on: ubuntu-20.04

        steps:
            # Clone
            - uses: actions/checkout@v4.1.0
              with:
                  repository: ScratchAddons/ScratchAddons
                #   sparse-checkout: |
                #       addons/*/addon.json
                #       addons/addons.json
                #   sparse-checkout-cone-mode: false
                #   fetch-tags: true
                  fetch-depth: 0
            - run: git fetch --tags
            # Checkout
            - run: VERSION=${{ inputs.Version || '$(git describe --tags $(git rev-list --tags --max-count=1))' }}
            - run: git checkout ${{ env.VERSION || '$VERSION' }}
            # Get package
            - run: mkdir dist
            - run: echo "{\"name\":\"@sa-community/addons-data\",\"version\":\"${{ env.VERSION || '$VERSION' }}\",\"description\":Scratch Addons\" addons data\",\"homepage\":\"https://github.com/scratchaddons-community\",\"repository\":\"git+https://github.com/scratchaddons-community/addons-data-script\",\"license\":\"GPLv3\",\"maintainers\":[\"RedGuy12\"],\"main\":\"addons.json\"}" > dist/package.json
            # Get addons
            - run: |
                  jq -c 'map(select(startswith("//") | not) | {addon: ., content: (try input catch null)})' addons/addons.json $(jq -r 'map(select(startswith("//") | not) | "addons/" + . + "/addon.json") | join(" ")' addons/addons.json) >> dist/addons.json
            # Publish
            - uses: actions/setup-node@v3
              with:
                  registry-url: "https://registry.npmjs.org"
            # - run: npm publish
            #   working-directory: dist
            #   env:
            #       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
